export type Data = {
    id: number;
    str: string;
}

export const books_data: Data[] = [
    { id: 1, str: "Moby Dick" },
    { id: 2, str: "Pinocchio" },
    { id: 3, str: "To Kill a Mockingbird" },
    { id: 4, str: "1984" },
    { id: 5, str: "The Great Gatsby" },
    { id: 6, str: "Pride and Prejudice" },
    { id: 7, str: "The Catcher in the Rye" },
    { id: 8, str: "One Hundred Years of Solitude" },
    { id: 9, str: "The Lord of the Rings" },
    { id: 10, str: "The Hobbit" },
    { id: 11, str: "Harry Potter and the Sorcerer's Stone" },
    { id: 12, str: "The Chronicles of Narnia" },
    { id: 13, str: "Brave New World" },
    { id: 14, str: "The Grapes of Wrath" },
    { id: 15, str: "Fahrenheit 451" },
    { id: 16, str: "The Odyssey" },
    { id: 17, str: "The Iliad" },
    { id: 18, str: "Jane Eyre" },
    { id: 19, str: "Wuthering Heights" },
    { id: 20, str: "Frankenstein" },
    { id: 21, str: "Dracula" },
    { id: 22, str: "The Picture of Dorian Gray" },
    { id: 23, str: "The Scarlet Letter" },
    { id: 24, str: "The Count of Monte Cristo" },
    { id: 25, str: "Anna Karenina" },
    { id: 26, str: "War and Peace" },
    { id: 27, str: "The Brothers Karamazov" },
    { id: 28, str: "Crime and Punishment" },
    { id: 29, str: "The Three Musketeers" },
    { id: 30, str: "Les Misérables" },
    { id: 31, str: "The Jungle" },
    { id: 32, str: "The Sound and the Fury" },
    { id: 33, str: "In Search of Lost Time" },
    { id: 34, str: "A Tale of Two Cities" },
    { id: 35, str: "The Gruffalo" },
    { id: 36, str: "The Very Hungry Caterpillar" },
    { id: 37, str: "Where the Wild Things Are" },
    { id: 38, str: "The Cat in the Hat" },
    { id: 39, str: "Charlotte's Web" },
    { id: 40, str: "Green Eggs and Ham" },
    { id: 41, str: "The Little Prince" },
    { id: 42, str: "Alice's Adventures in Wonderland" },
    { id: 43, str: "The Hobbit" },
    { id: 44, str: "The Chronicles of Narnia" },
    { id: 45, str: "The Hunger Games" },
    { id: 46, str: "The Da Vinci Code" },
    { id: 47, str: "The Girl with the Dragon Tattoo" },
    { id: 48, str: "The Fault in Our Stars" },
    { id: 49, str: "Gone with the Wind" },
    { id: 50, str: "The Color Purple" },
];